// Code generated by Icestudio 0.3.3
// Tue, 27 Nov 2018 20:48:33 GMT

`default_nettype none

module main (
 input v873d49,
 output v89c3d3,
 output [0:7] vinit
);
 wire w0;
 wire w1;
 assign w0 = v873d49;
 assign v89c3d3 = w1;
 main_ve759f9 ve759f9 (
  .in(w0),
  .out(w1)
 );
 assign vinit = 8'b00000000;
endmodule

module main_ve759f9 (
 input in,
 output out
);
 
 assign out=~in;
endmodule
