// Code generated by Icestudio 0.3.3
// Thu, 15 Nov 2018 15:43:47 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 350;                             //Cambio mi duración del test a 10+10+3+2= 25*10 = 250 ns y un poco más --> 350 ns de duración del test 
 // Input/Output
 reg in;
 wire out;
 
 // Module instance
 main MAIN (
  .v873d49(in),
  .v89c3d3(out)
 );
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  in = 0;                                               //Añado aquí mis entradas para chequear mi módulo NOT
  #10 in=1;
  #10 in=0;
  #3  in=1;
  #2  in=0;
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
