// Code generated by Icestudio 0.3.3
// Mon, 15 Oct 2018 06:07:41 GMT

`default_nettype none

module main (
 input vdda667,
 input v97b64a,
 output v358526,
 output [0:4] vinit
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v97b64a;
 assign v358526 = w1;
 assign w2 = vdda667;
 main_v67385c v67385c (
  .clk(w0),
  .q(w1),
  .d(w2)
 );
 assign vinit = 5'b00000;
endmodule

module main_v67385c (
 input d,
 input clk,
 output q
);
 
 reg q=1'b1;
 
 always @(posedge clk)
 q<=d;
   
 
 
 
 
endmodule
