// Code generated by Icestudio 0.3.2-beta
// Sat, 14 Apr 2018 21:34:52 GMT

`default_nettype none

module main (
 output v52917d
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign v52917d = w2;
 v806539 v2e2e35 (
  .v1bf25e(w0),
  .vfe1eb9(w3)
 );
 v806539 vf30ac7 (
  .vfe1eb9(w0),
  .v1bf25e(w1)
 );
 v806539 v543dc1 (
  .vfe1eb9(w1),
  .v1bf25e(w2)
 );
 vb734f6 v85bb26 (
  .v9fb85f(w3)
 );
endmodule

module v806539 (
 input vfe1eb9,
 output v1bf25e
);
 wire w0;
 wire w1;
 assign v1bf25e = w0;
 assign w1 = vfe1eb9;
 v806539_v8a0042 v8a0042 (
  .out(w0),
  .in(w1)
 );
endmodule

module v806539_v8a0042 (
 input in,
 output out
);
 
 buf buffer(out,in);
 
 
endmodule

module vb734f6 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vb734f6_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

module vb734f6_vb2eccd (
 output q
);
 //-- Bit constante a 1
 assign q = 1'b1;
 
 
endmodule
