// Code generated by Icestudio 0.3.2
// Sat, 05 May 2018 21:33:12 GMT

`default_nettype none

module counterM14 (
 input en,
 input reset,
 input clk,
 output [3:0] count
);
 
 reg[3:0] count;
 
 always @(posedge clk, posedge reset)
 begin
   if(reset)
     count <=4'd0;
   else if (en && count ==4'd13) count <=4'd0;
   else if (en) count <= count + 1;
   
 end
endmodule
