// Code generated by Icestudio 0.3.3
// Sat, 01 Dec 2018 21:47:30 GMT

`default_nettype none

module main #(
 parameter vea947b = 5
) (
 input v1d1841,
 input v4d66c8,
 output vfa9c3f,
 output [0:4] vinit
);
 localparam p0 = vea947b;
 wire w1;
 wire w2;
 wire w3;
 assign vfa9c3f = w1;
 assign w2 = v1d1841;
 assign w3 = v4d66c8;
 v94027a #(
  .va1edee(p0)
 ) vc2b514 (
  .v19bd79(w1),
  .vdb65bd(w2),
  .ve9fb46(w3)
 );
 assign vinit = 5'b00000;
endmodule

module v94027a #(
 parameter va1edee = 0
) (
 input vdb65bd,
 input ve9fb46,
 output v19bd79
);
 localparam p1 = va1edee;
 wire w0;
 wire w2;
 wire w3;
 assign v19bd79 = w0;
 assign w2 = ve9fb46;
 assign w3 = vdb65bd;
 v94027a_v8c8712 #(
  .t(p1)
 ) v8c8712 (
  .u(w0),
  .clk(w2),
  .reset(w3)
 );
endmodule

module v94027a_v8c8712 #(
 parameter t = 0
) (
 input reset,
 input clk,
 output u
);
 // falling pulse in t
 // t ciclos de reloj a 1 y
 // cambia a 0.
 
 localparam num_periods=t;
 
 reg[7:0] contador=0;
 reg u=1'b1;
 
 
 always @(posedge clk)
 if(reset) contador<=0;
 else if(contador >= num_periods-1)
  begin
  u <=1'b0;
  contador <= contador;
  end
 else
  begin
   u<=1'b1;
   contador=contador+1;
  end
  
  
  
  
endmodule
