// Code generated by Icestudio 0.3.2-beta
// Thu, 22 Mar 2018 20:42:49 GMT

`default_nettype none

module main (
 input v476ca1,
 input vc114a5,
 input va18244,
 output v019e5a,
 output [0:3] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign w2 = v476ca1;
 assign w3 = vc114a5;
 assign w4 = va18244;
 assign v019e5a = w5;
 vb8ea79 v6a98ff (
  .vcbab45(w0),
  .v0e28cb(w2),
  .v3ca442(w3)
 );
 v3f1160 vf19fb7 (
  .v0e28cb(w0),
  .v3ca442(w1),
  .vcbab45(w5)
 );
 v7f3e9f v0341db (
  .vcbab45(w1),
  .v0e28cb(w4)
 );
 assign vinit = 4'b0000;
endmodule

module vb8ea79 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vb8ea79_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

module vb8ea79_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta AND
 
 //-- module and (input wire a, input wire b,
 //--             output wire c);
 
 assign c = a & b;
 
 //-- endmodule
endmodule

module v3f1160 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v3f1160_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

module v3f1160_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta OR
 
 //-- module or (input wire a, input wire b,
 //--            output wire c);
 
 
 assign c = a | b;
 
 
 //-- endmodule
endmodule

module v7f3e9f (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v7f3e9f_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

module v7f3e9f_vd54ca1 (
 input a,
 output c
);
 //-- Puerta NOT
 
 //-- module (input wire a, output wire c);
 
 
 assign c = ~a;
 
 
 //-- endmodule
 
endmodule
