// Code generated by Icestudio 0.3.3
// Thu, 15 Nov 2018 23:00:52 GMT

`default_nettype none

module main (
 input vfad476,
 input v6d9635,
 input vc75b73,
 input v343bc5,
 output vdbf484,
 output [0:7] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign vdbf484 = w2;
 assign w3 = vfad476;
 assign w4 = v6d9635;
 assign w5 = vc75b73;
 assign w6 = v343bc5;
 v816138 v97f5fb (
  .vcbab45(w0),
  .v0e28cb(w3),
  .v3ca442(w4)
 );
 v816138 v0d0f35 (
  .vcbab45(w1),
  .v0e28cb(w5),
  .v3ca442(w6)
 );
 vb2090f v7a2694 (
  .v0e28cb(w0),
  .v3ca442(w1),
  .vcbab45(w2)
 );
 assign vinit = 8'b00000000;
endmodule

module v816138 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v816138_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

module v816138_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta OR
 
 //-- module and (input wire a, input wire b,
 //--             output wire c);
 
 assign c = a | b;
 
 //-- endmodule
endmodule

module vb2090f (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vb2090f_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

module vb2090f_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta AND
 
 //-- module and (input wire a, input wire b,
 //--             output wire c);
 
 assign c = a & b;
 
 //-- endmodule
endmodule
