// Code generated by Icestudio 0.3.3
// Thu, 15 Nov 2018 23:01:08 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 500;
 
 // Input/Output
 reg a;
 reg b;
 reg c;
 reg d;
 wire out;
 
 // Module instance
 main MAIN (
  .vfad476(a),
  .v6d9635(b),
  .vc75b73(c),
  .v343bc5(d),
  .vdbf484(out)
 );
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  a = 0;  b = 0;  c = 0;  d = 0;
  #2 a=0; b=0; c=0; d=1;
  #2 a=0; b=0; c=0; d=1;
  #2 a=0; b=0; c=1; d=0;
  #2 a=0; b=0; c=1; d=1;
  #2 a=0; b=1; c=0; d=0;
  #2 a=0; b=1; c=0; d=1;
  #2 a=0; b=1; c=1; d=0;
  #2 a=0; b=1; c=1; d=1;
  #2 a=1; b=0; c=0; d=0;
  #2 a=1; b=0; c=0; d=1;
  #2 a=1; b=0; c=1; d=0;
  #2 a=1; b=0; c=1; d=1;
  #2 a=1; b=1; c=0; d=0;
  #2 a=1; b=1; c=0; d=1;
  #2 a=1; b=1; c=1; d=0;
  #2 a=1; b=1; c=1; d=1;
  
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
