// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main #(
 parameter v0fe8ab = 3,
 parameter v823f1c = -5
) (
 output [3:0] ve267ba,
 output [0:0] vinit
);
 localparam p2 = v823f1c;
 localparam p3 = v0fe8ab;
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:3] w4;
 assign ve267ba = w4;
 v656d05 #(
  .vb061d7(p3)
 ) v219712 (
  .vda9708(w1)
 );
 v656d05 #(
  .vb061d7(p2)
 ) vc43618 (
  .vda9708(w0)
 );
 main_vabf85c vabf85c (
  .b(w0),
  .a(w1),
  .d(w4)
 );
 assign vinit = 1'b0;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v656d05 #(
 parameter vb061d7 = 0
) (
 output [3:0] vda9708
);
 localparam p0 = vb061d7;
 wire [0:3] w1;
 assign vda9708 = w1;
 v656d05_v49c8a7 #(
  .n(p0)
 ) v49c8a7 (
  .num(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- 4 bits constante  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Constante 4 bits
/*-------------------------------------------------*/

module v656d05_v49c8a7 #(
 parameter n = 0
) (
 output [3:0] num
);
 
 assign num=n;
endmodule

module main_vabf85c (
 input [3:0] a,
 input [3:0] b,
 output [3:0] d
);
 
 
 always @(a or b)
 
 begin:LABEL
 // A Sequential block requires a label if local
 //declarations are present
 
 integer a1,b1,d; //integer 32 bits signed
 a1 <= a;
 b1 <= b;
 d <= a+b;
 
 end
endmodule
