// Code generated by Icestudio 0.3.2-beta
// Tue, 17 Apr 2018 22:46:58 GMT

`default_nettype none

module main (
 input v3a281f,
 input vaef0cd,
 input vdcdfc1,
 output vee2768,
 output [0:4] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign vee2768 = w0;
 assign w1 = vdcdfc1;
 assign w2 = v3a281f;
 assign w3 = vaef0cd;
 main_v60237d v60237d (
  .pin(w0),
  .En(w1),
  .ToPin(w2),
  .FromPin(w3)
 );
 assign vinit = 5'b00000;
endmodule

module main_v60237d (
 input ToPin,
 input FromPin,
 input En,
 output pin
);
 // Output Triestado - Input directo
 
 SB_IO #(
       .PIN_TYPE(6'b1010_01),
       .PULLUP(1'b0)
       //.NEG_TRIGGER(1'b0),
       //.IO_STANDARD(SB_LVCMOS)
   ) ioSB (
       .PACKAGE_PIN(pin),
       //.LATCH_INPUT_VALUE(1'b1),
       .CLOCK_ENABLE(1'b0),
       .INPUT_CLK(1'b0),
       .OUTPUT_CLK(1'b0),
       .OUTPUT_ENABLE(En),
       .D_OUT_0(ToPin),
       .D_IN_0(FromPin)
        );
endmodule
