// Code generated by Icestudio 0.3.0-rc
// Sun, 28 May 2017 07:55:31 GMT

`default_nettype none

module main #(
 parameter v214998 = 1,
 parameter v47de66 = 2
) (
 input vclk,
 output [0:4] vinit
);
 localparam p0 = v214998;
 localparam p1 = v47de66;
 wire w2;
 assign w2 = vclk;
 main_v4ede05 #(
  .a(p0),
  .b(p1)
 ) v4ede05 (
  .clk(w2)
 );
 assign vinit = 5'b00000;
endmodule

module main_v4ede05 #(
 parameter a = 0,
 parameter b = 0
) (
 input clk,
 output [31:0] out,
 output [31:0] outSum
);
 
 integer out,outSum;
 
 always @(posedge clk)
 begin
 out <= a*b;
 outSum <= a+b;
 end
endmodule
