// Code generated by Icestudio 0.3.2-beta
// Mon, 09 Apr 2018 23:02:54 GMT

`default_nettype none

module Display (
 input clk,
 output [6:0] display /*synthesis LOC="P20,P19,P18,P17,P16,P15,P14"*/
);
 
 reg[2:0] cuenta=4'b000;
 reg[6:0] display=7'b 1111110;
 
 always @(posedge clk)
 begin
 
 cuenta<=cuenta+1;
 
     // Case statement implements a logig truth table
     case(cuenta)
         3'b000:display <=7'b 1111110;  //a,b,c,d,e,f,g
         3'b001:display <=7'b 0110000;
         3'b010:display <=7'b 1101101;
         3'b011:display <=7'b 1111001;
         3'b100:display <=7'b 0110011;
         3'b101:display <=7'b 1011011;
         3'b110:display <=7'b 1011111;
         3'b111:display <=7'b 1110000;
         
         default:display <=7'b 1111110;
     endcase
 end
 
 
endmodule
