// Code generated by Icestudio 0.3.3
// Sat, 01 Dec 2018 20:54:29 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 200;
 
 // TODO: edit the module parameters here
 // e.g. localparam constant_value = 1;
 localparam constant_Inicio_En =5 ;
 
 // Input/Output
 reg reloj;
 reg reset;
 wire escalon;
 
 // Module instance
 main #(
  .vf7cfab(constant_Inicio_En)
 ) MAIN (
  .vd3e926(reloj),
  .v4f007a(reset),
  .vf23155(escalon)
 );
 
 always #1 reloj=~reloj;        // Genero reloj
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  reloj = 0;
  reset = 0;
  #20 reset=1;
  #2 reset=0;
  #19 reset=1;
  #2  reset=0;
  #21 reset=1;
  #2  reset=0;
  
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
