// Code generated by Icestudio 0.3.2
// Sun, 06 May 2018 21:04:30 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 100;
 
 // Input/Output
 output reg clk;
 input wire [23:0] tone;
 input wire [14:0] counter;
 input wire speaker;
 
 // Module instance
 Ambulancia sonido(
  .clk(clk),
  .tone(tone),
  .counter(counter),
  .speaker(speaker)
 );
 
 // Clock signal
 always #1 clk = ~clk;
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  clk = 0;
  tone=0;
  counter=0;
  speaker=0;
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
