// Code generated by Icestudio 0.3.2
// Sun, 06 May 2018 21:03:46 GMT

`default_nettype none

module Ambulancia(
 input clk,
 output [23:0] tone,
 output [14:0] counter,
 output speaker
);
 
 parameter clkdivider = 12000000/440/2; //Cálculo para el 50% dutty
 
 reg [23:0] tone;
 always @(posedge clk) tone <= tone+1;
 
 reg [14:0] counter;
 always @(posedge clk) if(counter==0) counter <= (tone[23] ? clkdivider-1 : clkdivider/2-1); else counter <= counter-1;
 
 reg speaker;
 always @(posedge clk) if(counter==0) speaker <= ~speaker;
 
endmodule
