// Code generated by Icestudio 0.7.1w202108130708

`default_nettype none

//---- Top entity
module main (
 output [0:4] vinit
);
 main_v04e04a v04e04a (
 
 );
 assign vinit = 5'b00000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v04e04a
;
 
 tri [15:0] busa;
 wand w;
 wor s;
endmodule
