// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main #(
 parameter v5ef9b3 = -1,
 parameter ve03011 = 1
) (
 output v01b306,
 output vb781d5,
 output [0:5] vinit
);
 localparam p3 = v5ef9b3;
 localparam p5 = ve03011;
 wire w0;
 wire w1;
 wire [0:31] w2;
 wire [0:31] w4;
 wire [0:31] w6;
 wire [0:31] w7;
 assign v01b306 = w0;
 assign vb781d5 = w1;
 assign w6 = w4;
 assign w7 = w2;
 vc89775 #(
  .vb061d7(p3)
 ) vc1d971 (
  .vaa2e3c(w2)
 );
 main_v3f05f0 v3f05f0 (
  .z(w0),
  .a(w2),
  .b(w6)
 );
 main_v3ed786 v3ed786 (
  .z1(w1),
  .b1(w4),
  .a1(w7)
 );
 vc89775 #(
  .vb061d7(p5)
 ) vf02eac (
  .vaa2e3c(w4)
 );
 assign vinit = 6'b000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module vc89775 #(
 parameter vb061d7 = 0
) (
 output [31:0] vaa2e3c
);
 localparam p0 = vb061d7;
 wire [0:31] w1;
 assign vaa2e3c = w1;
 vc89775_v49c8a7 #(
  .n(p0)
 ) v49c8a7 (
  .num(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- 32 bits constant  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 32 bits constant
/*-------------------------------------------------*/

module vc89775_v49c8a7 #(
 parameter n = 0
) (
 output [31:0] num
);
 
 assign num=n;
endmodule

module main_v3f05f0 (
 input [31:0] a,
 input [31:0] b,
 output z
);
 
 
 assign z=a>b;
 
endmodule

module main_v3ed786 (
 input [31:0] a1,
 input [31:0] b1,
 output z1
);
 
 integer a2,b2;
 reg z1;
 
 always @(a1,b1)
 begin
   a2<=a1;
   b2<=b1;
   z1 <= a2>b2;
 end
 
 
 
endmodule
