// Code generated by Icestudio 0.3.2
// Wed, 02 May 2018 11:05:39 GMT

`default_nettype none

module RS (
 input S,
 input R,
 input reset,
 input clk,
 output q
);
 
 //SR Flop
 
 reg q;
 
 always @(posedge clk or posedge reset)
 begin
   if(reset) q<=1'b0;
   else if (S) q<=1'b1;
   else if (R) q<=1'b0;
 end
   
   
endmodule
