// Code generated by Icestudio 0.3.2-beta
// Mon, 19 Mar 2018 21:48:07 GMT

`default_nettype none

module main (
 input v59b961,
 input v341d0c,
 input vd21372,
 output v150ebc,
 output [0:3] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = v59b961;
 assign w1 = v341d0c;
 assign w2 = vd21372;
 assign v150ebc = w3;
 main_vd5ba31 vd5ba31 (
  .a(w0),
  .b(w1),
  .c(w2),
  .out(w3)
 );
 assign vinit = 4'b0000;
endmodule

module main_vd5ba31 (
 input a,
 input b,
 input c,
 output out
);
 
 
 wire d;
 
 assign d=a&b;
 assign out=d|c;
endmodule
