// Code generated by Icestudio 0.3.3
// Sun, 02 Dec 2018 23:08:46 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 1 ns


module main_tb
;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 100;
 
 // Input/Output
 reg clk;
 reg reset;
 reg in;
 wire Rising;
 
 // Module instance
 main MAIN (
  .va1feb1(clk),
  .v4e5c9f(reset),
  .vc9fba8(in),
  .vd9fe63(Rising)
 );
 
 // Clock signal
 always #0.5 clk = ~clk;
 
 initial begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  clk = 1;
  reset = 0;
  in = 0;
  #4 in=1;
  #5 in=0;
  #3 in=1;
  #1 in=0;
  #7 in=1;
  #1 reset=1;
  #1 reset=0;
  #4 in=0;
  
 
  #(DURATION) $display("End of simulation");
  $finish;
 end
 
endmodule
