// Code generated by Icestudio 0.3.3
// Sun, 02 Dec 2018 23:41:04 GMT

`default_nettype none

module main (
 input va1feb1,
 input v4e5c9f,
 input vc9fba8,
 output vd9fe63,
 output [0:4] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = va1feb1;
 assign vd9fe63 = w1;
 assign w2 = v4e5c9f;
 assign w3 = vc9fba8;
 v92a3ca v7432ea (
  .v02d455(w0),
  .v32443d(w1),
  .v4ae82c(w2),
  .v08bfd6(w3)
 );
 assign vinit = 5'b00000;
endmodule

module v92a3ca (
 input v02d455,
 input v4ae82c,
 input v08bfd6,
 output v32443d
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign v32443d = w0;
 assign w1 = v02d455;
 assign w2 = v4ae82c;
 assign w3 = v08bfd6;
 v92a3ca_v3523b6 v3523b6 (
  .Rising(w0),
  .clk(w1),
  .reset(w2),
  .in(w3)
 );
endmodule

module v92a3ca_v3523b6 (
 input clk,
 input reset,
 input in,
 output Rising
);
 
 reg Q1=0,Q2=0;
 
 //Biestable D donde capturo estado actual (in) y anterior (Q)
 always @(posedge clk)
 if(reset)
    begin
     Q1<=1'b1;
     Q2<=1'b1;
    end 
 else
    begin
      Q1<=in;
      Q2<=Q1;
    end
      
 
 //Con datos del estado actual ya anterior, realizando un circutio combinacional
 //puedo saber si la señal a cambiado y si ha subido o ha bajado el flanco.
 
 assign Rising  = (in & ~Q2) & ~reset; // Si in (Actual) es 1 pero antes (Q) era 0 --> Rising
endmodule
