// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main (
 input [7:0] vb31478,
 input v9d2436,
 input v97b64a,
 output [7:0] v95d949,
 output [0:4] vinit
);
 wire w0;
 wire w1;
 wire [0:7] w2;
 wire [0:7] w3;
 assign w0 = v9d2436;
 assign w1 = v97b64a;
 assign v95d949 = w2;
 assign w3 = vb31478;
 main_v67385c v67385c (
  .reset(w0),
  .clk(w1),
  .q(w2),
  .d(w3)
 );
 assign vinit = 5'b00000;
endmodule

/*-------------------------------------------------*/
/*--  D8 L&R  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Register using 8 bit + load + Reset
/*-------------------------------------------------*/

module main_v67385c (
 input [7:0] d,
 input reset,
 input clk,
 output [7:0] q
);
 
 reg[7:0] qi=0;
 
 always @(posedge clk or posedge reset)
 if(reset)
  qi<=0;
 else
  qi<=qi;
  
 assign q=qi;
 
 
 
endmodule
