// Code generated by Icestudio 0.3.0-rc
// Sun, 21 May 2017 23:23:10 GMT

// Testbench template

`default_nettype none
`define DUMPSTR(x) `"x.vcd`"
`timescale 10 ns / 10 ns 


module main_tb;
 
 // Simulation time: 100ns (10 * 10ns)
 parameter DURATION = 12;

 // Input/Output
 
 output reg clock=1;
 input wire fin;
 input wire[15:0] Fact;
 
 
 // Module instance
 factorial #(.number(5)) DUT_Factorial( .clk(clock), .factorial(Fact), .End(fin));
 
 always #1 clock=~clock;
 
 initial 
 begin
  // File were to store the simulation results
  $dumpfile(`DUMPSTR(`VCD_OUTPUT));
  $dumpvars(0, main_tb);
 
  // TODO: initialize the registers here
  // e.g. value = 1;
  // e.g. #2 value = 0;
  
 
  #(DURATION) $display("End of simulation");
  $display("Factorial = ",Fact);
  $finish;
 end
 
endmodule
