// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main #(
 parameter v784ccd = 1,
 parameter v6446fd = -7,
 parameter v77ec80 = 9
) (
 output [3:0] vbe9e7b,
 output [0:3] vinit
);
 localparam p3 = v784ccd;
 localparam p4 = v6446fd;
 localparam p5 = v77ec80;
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w6;
 wire [0:3] w7;
 assign vbe9e7b = w0;
 v656d05 #(
  .vb061d7(p3)
 ) v849356 (
  .vda9708(w2)
 );
 v0af222 v76e9d8 (
  .vbe732b(w1),
  .v61ef5a(w2),
  .v4590c2(w6)
 );
 v0af222 v6a36d5 (
  .vbe732b(w0),
  .v61ef5a(w1),
  .v4590c2(w7)
 );
 v656d05 #(
  .vb061d7(p4)
 ) v981c9f (
  .vda9708(w6)
 );
 v656d05 #(
  .vb061d7(p5)
 ) ve7d9b1 (
  .vda9708(w7)
 );
 assign vinit = 4'b0000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v656d05 #(
 parameter vb061d7 = 0
) (
 output [3:0] vda9708
);
 localparam p0 = vb061d7;
 wire [0:3] w1;
 assign vda9708 = w1;
 v656d05_v49c8a7 #(
  .n(p0)
 ) v49c8a7 (
  .num(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- 4 bits constante  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Constante 4 bits
/*-------------------------------------------------*/

module v656d05_v49c8a7 #(
 parameter n = 0
) (
 output [3:0] num
);
 
 assign num=n;
endmodule
//---- Top entity
module v0af222 (
 input [3:0] v61ef5a,
 input [3:0] v4590c2,
 output [3:0] vbe732b
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 assign w0 = v61ef5a;
 assign w1 = v4590c2;
 assign vbe732b = w2;
 v0af222_vde381d vde381d (
  .a(w0),
  .b(w1),
  .res(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Unsigned Sum 4 bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Unsigned Sum
/*-------------------------------------------------*/

module v0af222_vde381d (
 input [3:0] a,
 input [3:0] b,
 output [3:0] res
);
 
 
 assign res = a+b;
endmodule
