// Code generated by Icestudio 0.7.1w202109100309

`default_nettype none

//---- Top entity
module main #(
 parameter v784ccd = 1,
 parameter v6446fd = -7,
 parameter v77ec80 = 9
) (
 input vclk,
 output [3:0] vbe9e7b,
 output [0:3] vinit
);
 localparam p0 = v784ccd;
 localparam p1 = v6446fd;
 localparam p2 = v77ec80;
 wire [0:3] w3;
 wire [0:3] w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 assign vbe9e7b = w3;
 assign w8 = vclk;
 assign w9 = vclk;
 assign w9 = w8;
 v656d05 #(
  .vb061d7(p0)
 ) v849356 (
  .vda9708(w5)
 );
 v2d29ee ve4c331 (
  .v6969ed(w4),
  .v29647b(w5),
  .vb509ef(w6),
  .v85b632(w8)
 );
 v2d29ee v3016c3 (
  .v6969ed(w3),
  .v29647b(w4),
  .vb509ef(w7),
  .v85b632(w9)
 );
 v656d05 #(
  .vb061d7(p1)
 ) v981c9f (
  .vda9708(w6)
 );
 v656d05 #(
  .vb061d7(p2)
 ) ve7d9b1 (
  .vda9708(w7)
 );
 assign vinit = 4'b0000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module v656d05 #(
 parameter vb061d7 = 0
) (
 output [3:0] vda9708
);
 localparam p0 = vb061d7;
 wire [0:3] w1;
 assign vda9708 = w1;
 v656d05_v49c8a7 #(
  .n(p0)
 ) v49c8a7 (
  .num(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- 4 bits constante  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Constante 4 bits
/*-------------------------------------------------*/

module v656d05_v49c8a7 #(
 parameter n = 0
) (
 output [3:0] num
);
 
 assign num=n;
endmodule
//---- Top entity
module v2d29ee (
 input [3:0] v29647b,
 input [3:0] vb509ef,
 input v85b632,
 output [3:0] v6969ed
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire w2;
 wire [0:3] w3;
 assign w0 = v29647b;
 assign w1 = vb509ef;
 assign w2 = v85b632;
 assign v6969ed = w3;
 v2d29ee_vde381d vde381d (
  .a(w0),
  .b(w1),
  .clk(w2),
  .res(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Unsigned Sum 4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Unsigned Sum 4 bits
/*-------------------------------------------------*/

module v2d29ee_vde381d (
 input [3:0] a,
 input [3:0] b,
 input clk,
 output [3:0] res
);
 
 reg[3:0] res;
 
 always @(posedge clk)
 res <=a+b;
endmodule
