// Code generated by Icestudio 0.3.2-beta
// Wed, 04 Apr 2018 19:35:55 GMT

`default_nettype none

module main (
 output vf8205e,
 output v0a6a09,
 output vcf7b87,
 output [0:1] vinit
);
 wire w0;
 wire w1;
 wire w2;
 assign v0a6a09 = w0;
 assign vcf7b87 = w1;
 assign vf8205e = w2;
 main_vadfe67 vadfe67 (
  .o(w0)
 );
 main_vae4084 vae4084 (
  .e(w1)
 );
 vaa2e20 v72d5c0 (
  .v5f7bb9(w2)
 );
 assign vinit = 2'b00;
endmodule

module vaa2e20 (
 output v5f7bb9
);
 wire w0;
 assign v5f7bb9 = w0;
 vaa2e20_v7d3b68 v7d3b68 (
  .x(w0)
 );
endmodule

module vaa2e20_v7d3b68 (
 output x
);
 
 //@include define01.v
 
 assign x=`TR;
endmodule

module main_vadfe67 (
 output o
);
 
 `define TR 1
 
 assign o=`TR;
endmodule

module main_vae4084 (
 output e
);
 
 
 assign e=`TR;
endmodule
