// Code generated by Icestudio 0.3.2
// Wed, 02 May 2018 10:40:24 GMT

`default_nettype none

module DFlopENCL (
 input D,
 input EN,
 input clear_n,
 input reset,
 input clk,
 output Q
);
 
 reg Q;
 
 always @(posedge clk or posedge reset)
 begin
     if(reset)               Q<=1'b0;
     else if (clear_n==1'b0) Q<=1'b0;
     else if (EN)            Q<=D;
     else                    Q<=Q;
 end
endmodule
