// Code generated by Icestudio 0.3.2-beta
// Wed, 21 Mar 2018 22:26:58 GMT

`default_nettype none

module main (
 input v6b373b,
 input vdc365b,
 input v1e8eaf,
 output v02b1d1,
 output [0:4] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = v6b373b;
 assign w1 = vdc365b;
 assign w2 = v1e8eaf;
 assign v02b1d1 = w3;
 main_vd5ba31 vd5ba31 (
  .a(w0),
  .b(w1),
  .c(w2),
  .out(w3)
 );
 assign vinit = 5'b00000;
endmodule

module main_vd5ba31 (
 input a,
 input b,
 input c,
 output out
);
 
 
 wire d;
 
 assign d=a&b;
 assign out=d|c;
endmodule
